datasets:
  - adult
  - bank-marketing
  - aps_failure
  - electricity
  - covertype
  - dry-bean-dataset
  - crop-recommendation
  - breast-cancer-wisconsin
  - heart-disease
  - diabetes
  - haberman
  - ionosphere
  - sonar
  - credit-g
  - default-of-credit-card-clients
  - mushroom
  - magic-telescope
  - spambase
  - wine-quality-red
  - rice-cammeo-and-osmancik
